 export enum LIC {    
    REG_LICITACAO    = "LIC/REG_LICITACAO",
    CONTRATO_RESC    = "LIC/CONTRATO_RESC",
    SITUACAO_PROCED  = "LIC/SITUACAO_PROCED",
    ADESAO_REG_PREC  = "LIC/ADESAO_REG_PREC",
    RETIFICAHOMOLOG  = "LIC/RETIFICAHOMOLOG",
    CONTRATO_ADT     = "LIC/CONTRATO_ADT",
    DISPENSA_INEXIG  = "LIC/DISPENSA_INEXIG",
    LICITACAOFASE1   = "LIC/LICITACAOFASE1",
    LICITACAOFASE2   = "LIC/LICITACAOFASE2",
    CONTRATO_INI     = "LIC/CONTRATO_INI"
}